### ISSUE TITLE
Planning the basic design

### ISSUE THREAD

**Issue by sobiawaqar** [Roman-Hal/Soaaro#3]

**Comment by sobiawaqar** [comment]
- [ ] what features are needed
- [ ] login page
- [ ] Home Page
- [ ] graduate area / page
     - [ ]  plans
     - [ ] goals (SMART goals)
     - [ ] progress
     - [ ] overview
     
- [ ] mentor area / page
- [ ] plans 
      - [ ]  list of goals
      - [ ] feedback page through invitation
- [ ] Header / footer
- [ ] Notification system

**Comment by Aaron-CYF** [comment]
We are creating a plan by dividing/breaking down the project into smaller tickets/issues on github project board.
#2
