### ISSUE TITLE
Creating links in the slack chat

### ISSUE THREAD

**Issue by Roman-Hal** [Roman-Hal/Soaaro#8]
- [x] dev starter kit
- [x] Jitsi meeting link
- [x] repository link
- [x] project dashboard link
- [x] figma mindmap link

**Comment by sobiawaqar** [comment]
Add Mind map (Aaron)

**Comment by Aaron-CYF** [comment]
> Add Mind map (Aaron)

added bookmark link to mindmap in both slack chat and slack team channel.

**Comment by sobiawaqar** [comment]
The links are pinned successfully.
